/* confdefs.h */
#define PACKAGE_NAME "souffle"
#define PACKAGE_TARNAME "souffle"
#define PACKAGE_VERSION "1.6.2-842-gca4aa758"
#define PACKAGE_STRING "souffle 1.6.2-842-gca4aa758"
#define PACKAGE_BUGREPORT "souffle-talk@googlegroups.com"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define PACKAGE "souffle"
#define VERSION "1.6.2-842-gca4aa758"
#define HAVE_NCURSES_H 1
