version: '3.3'

networks:
  app-tier:
    driver: overlay

services:
  zookeeper:
    image: 'zookeeper:3.5'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
        KAFKA_LISTENERS: LISTENER_INTER://:29092
        KAFKA_ADVERTISED_LISTENERS: LISTENER_INTER://kafka:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTER:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTER
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        # KAFKA_REPLICA_FETCH_MAX_BYTES: 2147483647
        # KAFKA_MESSAGE_MAX_BYTES: 2147483647
        # KAFKA_MAX_MESSAGE_BYTES: 2147483647
        # KAFKA_MESSAGE_MAX_BYTES: 2147483647
        # KAFKA_FETCH_MAX_BYTES: 2147483647
    networks:
      - app-tier


