apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    app: kafka
    tier: backend
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_LISTENERS
            value: "LISTENER_INTER://:29092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "LISTENER_INTER://kafka-cluster:29092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "LISTENER_INTER:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "LISTENER_INTER"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
        resources:
          requests:
            memory: "400M"
            cpu: "0.3"
          limits:
            memory: "800M"
            cpu: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    tier: backend
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: zooport1
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper:3.5
        ports:
          - containerPort: 2181
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
        resources:
          requests:
            memory: "100M"
            cpu: "0.03"
          limits:
            memory: "200M"
            cpu: "0.2"
---